#!/bin/bash

TOPIC=${1}
DURATION=${2:-10} # 回数

rostopic echo -p -n $DURATION $TOPIC > /tmp/topic_data.csv

sum=0
count=0
{
  read # 先頭のヘッダー行を読み飛ばす
  while IFS=, read -r timestamp value
  do
    # 科学記法を通常の浮動小数点数に変換
    value=$(echo $value | awk '{printf "%f", $0}')
    sum=$(echo "$sum + $value" | bc)
    ((count++))
  done
} < /tmp/topic_data.csv

if [ $count -gt 0 ]; then
  average=$(echo "scale=10; $sum / $count" | bc)
  echo "Average: $average"
else
  echo "No data received."
fi

rm /tmp/topic_data.csv
